// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arecopcgvzzttgqqsvhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyZWNvcGNndnp6dHRncXFzdmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMzAzNTMsImV4cCI6MjA2NTYwNjM1M30.dcMHvBOJlnukKTukC3XYsDPz0LGAu9CJj9CuiJWjz-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);